### ISSUE TITLE
根目录index.php多写了一个“.”报错

### ISSUE THREAD

**Issue by meng-luo** [5ime/API-Admin#14]
![image](https://user-images.githubusercontent.com/79274361/151558317-967f590c-2e7d-4197-9e6d-43e25604e7c7.png)
![image](https://user-images.githubusercontent.com/79274361/151558359-0df0cbf3-e9aa-4810-8376-79fc5bfedc89.png)

**Comment by meng-luo** [comment]
## 可能bug有点多
### 安装时报错
- config目录下database.php权限不足

![image](https://user-images.githubusercontent.com/79274361/151561391-698ad0b1-f133-46ba-bb51-31561991066e.png)

### 调用时报错

- 可能是我开了强制https的关系

![image](https://user-images.githubusercontent.com/79274361/151563528-bd35a7ca-cd9f-4a72-ac2e-9dc552330754.png)

### 后端日志获取失败

- 这个日志路径不知道怎么写，写了绝对路径写了导致cpu占用100%

![image](https://user-images.githubusercontent.com/79274361/151564639-a3dd358b-0d40-4446-af02-9cdaa32d4136.png)

**Comment by 5ime** [comment]
1. `database.php`权限不足未复现，所有文件均为`755`
2. 调用已修复
3. 如果你用的宝塔请确保`.user.ini`未进行跨目录限制
