### ISSUE TITLE
符号被我吃掉惹

### ISSUE THREAD

**Issue by Cha-Shao** [5ime/API-Admin#15]
https://docs.tenapi.cn/img.html#%E8%B0%83%E7%94%A8%E6%95%88%E6%9E%9C
![image](https://user-images.githubusercontent.com/73894257/151711839-aee175f8-b618-4941-a0a9-27f4a5b0b6d1.png)
少了个"="

**Comment by 5ime** [comment]
由于源文件找不到了，目前无解。
