### ISSUE TITLE
后台提交新API接口失败

### ISSUE THREAD

**Issue by xmkjw63** [5ime/API-Admin#18]
如题，一直卡着mdui转圈圈,NetWork显示如图
![image](https://user-images.githubusercontent.com/55618195/169695153-e6ffeac6-7695-4124-ab31-876e1e916b89.png)
![image](https://user-images.githubusercontent.com/55618195/169695161-c97f720b-29f8-4943-9326-8f0c20b66544.png)
跳转404但是返回500
这是什么情况？

**Comment by 5ime** [comment]
可以开启调试模式 `config/app.php` ，看看具体为什么报错
```
  'app_debug'              => false,
  //改为
  'app_debug'              => true,
```

**Comment by xmkjw63** [comment]
> 可以开启调试模式 `config/app.php` ，看看具体为什么报错
> 
> ```
>   'app_debug'              => false,
>   //改为
>   'app_debug'              => true,
> ```
有试过 没啥用 还是跳转404
![image](https://user-images.githubusercontent.com/55618195/169695785-212db938-7a50-4bd6-bfd1-52e98ff7ba81.png)

**Comment by 5ime** [comment]
本地试了一下，没发现500的情况，麻烦发一下表单数据。

**Comment by xmkjw63** [comment]
> Reference in new
谢谢大佬 解决了

**Comment by xmkjw63** [comment]
问题在于Mysql5.7的严格模式 不能有空NULL
建议大佬这里稍微改下
![image](https://user-images.githubusercontent.com/55618195/169696255-aefaeafd-5e96-4bb9-b6d2-36568c3d2da6.png)
针对mysql5.7

**Comment by 5ime** [comment]
好的，感谢提醒
