### ISSUE TITLE
最新请求数据获取失败，请检查日志文件是否可以被访问！

### ISSUE THREAD

**Issue by pengwangzai** [5ime/API-Admin#23]
请问这个日志路径怎么填写
后台一直弹出最新请求数据获取失败，请检查日志文件是否可以被访问！

**Comment by 5ime** [comment]
操作指南在这 https://github.com/5ime/API-Admin/wiki
近期正在修复这些问题 建议直接下载仓库代码使用（已解决） 不要下载release里面的
