### ISSUE TITLE
带特殊字符的QQ昵称无法正常获取

### ISSUE THREAD

**Issue by imaegoo** [5ime/API-Admin#6]
### 请求

https://tenapi.cn/qqname/?qq=492927960

### 响应

```
{
    "code": 200,
    "imgurl": "https://q2.qlogo.cn/headimg_dl?dst_uin=492927960&spec=100",
    "name": "方"
}
```

### 实际昵称

![图片](https://user-images.githubusercontent.com/20182252/106981321-c99cfd00-679c-11eb-941c-cb7ed14aaaf7.png)

**Comment by imaegoo** [comment]
来自 imaegoo/twikoo#114 的反馈

> 我的QQ昵称有特殊字符“ྉ”，无法正确获取昵称

**Comment by 5ime** [comment]
获取昵称是爬取的QQ官方接口 官方接口那边返回不出:(
https://r.qzone.qq.com/fcg-bin/cgi_get_portrait.fcg?get_nick=1&uins=492927960
~~~
portraitCallBack({
  "492927960": [
    "http://qlogo1.store.qq.com/qzone/492927960/492927960/100",
    861,
    -1,
    0,
    0,
    0,
    "方",
    0
  ]
})
~~~

**Comment by imaegoo** [comment]
> 获取昵称是爬取的QQ官方接口 官方接口那边返回不出:(
> https://r.qzone.qq.com/fcg-bin/cgi_get_portrait.fcg?get_nick=1&uins=492927960
> 
> ```
> portraitCallBack({
>   "492927960": [
>     "http://qlogo1.store.qq.com/qzone/492927960/492927960/100",
>     861,
>     -1,
>     0,
>     0,
>     0,
>     "方",
>     0
>   ]
> })
> ```

@5ime 那就先不管了把，我搜索了一圈也没有找到哪个 API 能正确获取昵称中的特殊符号。
