### ISSUE TITLE
增添数据出错

### ISSUE THREAD

**Issue by songshuxiao** [5ime/API-Admin#7]
v1.2版本，可以修改已存在的数据
但无法增加数据，后台增添总提示
页面错误！请稍后再试～
ThinkPHP V5.0.24 { 十年磨一剑-为API开发设计的高性能框架 }
环境：Linux CentOS 8.2.2004 + Nginx 1.18.0 + PHP7.3 + MySQL 5.7.31

**Comment by 5ime** [comment]
未能复现:(
