### ISSUE TITLE
安装成功了，但是为什么访问域名会页面错误？

### ISSUE THREAD

**Issue by Critts** [5ime/API-Admin#9]

**Comment by 5ime** [comment]
伪静态设置了么

**Comment by Critts** [comment]
是这样吗？![QQ截图20210710135309](https://user-images.githubusercontent.com/81842641/125153459-6ddd0280-e186-11eb-8776-1fc061adaa5e.png)

**Comment by Critts** [comment]
> 伪静态设置了么

![QQ截图20210710135309](https://user-images.githubusercontent.com/81842641/125153582-518d9580-e187-11eb-92fe-bda9a2ad3a0f.png)
我是nginx的服务器，是这样配置吗？

**Comment by 5ime** [comment]
对的

**Comment by Critts** [comment]
> 对的

但是还是访问不了，请问还有那里需要注意的？

**Comment by 5ime** [comment]
NGINX除了伪静态 没什么要注意得了 运行目录也不需要设置

**Comment by 5ime** [comment]
PHP版本7.0-7.3吧

**Comment by Critts** [comment]
> PHP版本7.0-7.3吧

好

**Comment by Critts** [comment]
> PHP版本7.0-7.3吧

把php改成7.0就解决了

**Comment by Critts** [comment]
> PHP版本7.0-7.3吧

谢谢
